apiVersion: v1
items:
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    annotations:
      cert-manager.io/inject-ca-from-secret: cert-manager/cert-manager-webhook-ca
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"admissionregistration.k8s.io/v1","kind":"ValidatingWebhookConfiguration","metadata":{"annotations":{"cert-manager.io/inject-ca-from-secret":"cert-manager/cert-manager-webhook-ca"},"labels":{"app":"webhook","app.kubernetes.io/component":"webhook","app.kubernetes.io/instance":"cert-manager","app.kubernetes.io/name":"webhook","app.kubernetes.io/version":"v1.9.1"},"name":"cert-manager-webhook"},"webhooks":[{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"cert-manager-webhook","namespace":"cert-manager","path":"/validate"}},"failurePolicy":"Fail","matchPolicy":"Equivalent","name":"webhook.cert-manager.io","namespaceSelector":{"matchExpressions":[{"key":"cert-manager.io/disable-validation","operator":"NotIn","values":["true"]},{"key":"name","operator":"NotIn","values":["cert-manager"]}]},"rules":[{"apiGroups":["cert-manager.io","acme.cert-manager.io"],"apiVersions":["v1"],"operations":["CREATE","UPDATE"],"resources":["*/*"]}],"sideEffects":"None","timeoutSeconds":10}]}
    creationTimestamp: "2022-10-17T11:00:33Z"
    generation: 2
    labels:
      app: webhook
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/name: webhook
      app.kubernetes.io/version: v1.9.1
    name: cert-manager-webhook
    resourceVersion: "66568"
    uid: e7367c08-c6bf-460f-93cf-b4b9a9b6149a
  webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ3akNDQVVpZ0F3SUJBZ0lSQUp5VkpCa0hoNkNNRTdEQUNNd0dGdHN3Q2dZSUtvWkl6ajBFQXdNd0lqRWcKTUI0R0ExVUVBeE1YWTJWeWRDMXRZVzVoWjJWeUxYZGxZbWh2YjJzdFkyRXdIaGNOTWpJeE1ERTNNVEV3TURRdwpXaGNOTWpNeE1ERTNNVEV3TURRd1dqQWlNU0F3SGdZRFZRUURFeGRqWlhKMExXMWhibUZuWlhJdGQyVmlhRzl2CmF5MWpZVEIyTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFpQTJJQUJJdnFVMk50b3MvU2gybU56UHRTM01BYUw1YVQKVE9TcDhvR3VjdnBUbXJKY3VLNHZiMTdzRlNCNmJ3U3JodUVPMmNiTE5ISHpqOXlyK3NMVlVEM2xQdkFocU5GSgo3R3VUUlhCOG1YcXVkd2VxbTBQekQydko1eEhaci9tbkRIVFVwcU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trCk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZFVXFHeFhENGZac1ZvKzRUaEdPOXFTMTVBUnQKTUFvR0NDcUdTTTQ5QkFNREEyZ0FNR1VDTVFEKzZmcmVyazUySjVCeFRjL3Vvc1pkdWtDS3pZZS9SMEVFYWVnUQpnVGdHWXJXQW5SUnczd2tyRENrNzhVQUVpUGdDTUJoTlZYYVl2b004N2NWa29iZkc0WTNnSW1ibDZSVERmZitrCjNCckJ5bzVFbFZac0xha0w2dGdVODA0UjdZR1krUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: cert-manager-webhook
        namespace: cert-manager
        path: /validate
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: webhook.cert-manager.io
    namespaceSelector:
      matchExpressions:
      - key: cert-manager.io/disable-validation
        operator: NotIn
        values:
        - "true"
      - key: name
        operator: NotIn
        values:
        - cert-manager
    objectSelector: {}
    rules:
    - apiGroups:
      - cert-manager.io
      - acme.cert-manager.io
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - '*/*'
      scope: '*'
    sideEffects: None
    timeoutSeconds: 45
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    creationTimestamp: "2022-10-17T08:45:46Z"
    generation: 1
    labels:
      networking.gke.io/common-webhooks: "true"
    name: flowcontrol-guardrails.config.common-webhooks.networking.gke.io
    resourceVersion: "843"
    uid: d06ee512-88e1-4ac3-a2c5-9815eb9296f0
  webhooks:
  - admissionReviewVersions:
    - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRTW4yZ0VFQ1Z5VlFncDc0SU00VTh1REFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRd016UTJPR05pWWkxbE9Ua3hMVFJpTldZdFlUUTFOaTAzT0RFNE9EZzJOekEwTUdRdwpJQmNOTWpJeE1ERTNNRGMwTURBNVdoZ1BNakExTWpFd01Ea3dPRFF3TURsYU1DOHhMVEFyQmdOVkJBTVRKREF6Ck5EWTRZMkppTFdVNU9URXROR0kxWmkxaE5EVTJMVGM0TVRnNE9EWTNNRFF3WkRDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU10YVJuMW40OTl3WWJWQzdkVUtBcTNIaDUwM0xCZzRwUnNPNlN5UQo4dTFCR0s0VkdGYlhoZTNuaHpTaDRIcmo0VmlmRUJmLzY0ZFRjVUpNUHhjVEMwZ1JJVGtHMXhvQ1JhL3Rjb2twCjhYTVJWdC9hUHg5UzdDUlhoM0R3bEprRXJoSkF5TWZhdXNEVnBzZHNxTlNrcXByMVFoeXBIbHZGTHlwMEZQWEoKSVB2cE1VYXhkVkUwRlB3VTVnK29QOGFQOWkySTJxMFRWYWl1Zkg0VTFpMitIMnNHSjdFeUlOLzQ0Wm0rM1Y4TgpEd1J6OWNzcmJvb2tDUDlkZ0dVMDU5OEx5cGZQUDN1SDVLSEUrT0hQVWVLSkQ3cGQvdlovaWhmMGpLME82UVFQCmdHTlhuSDlGNUE1Nk1iTkhLOENYOWU4aytZY25DTHUxbktEWVV6clMvMDJYWjF0dkNXRkFIcFZ1M0lEQ1g0RkQKTEFoY3NmenhuTitKUW9tbGUvOVpzNnlieE0wUXpDdzJMQUVScjhmTkpHdmQ1YTNwRW14WUJKYWNpVGdhZGlUMwpFcUVMUUJqdk9JbVh0bllZR2xZZk40N1hzTkd3eWVzQzVYekxYdFBKanJtZEpCaW1ZWVNqSllGbnF5NnhTbmZPCi8yYmEvUWJIaEY2Nk5HdWFxNmpuRHhDMzB3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVIYjFoWWxiQ2VXZnMwUnMvMlZQS1RWaHNMSFV3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFGTDVEb2FDYS81RllxQnE5bjc5MDlDcnJmQjh5am1lZWlqeFdpM0phODNaCnZsNjA4V0pWQjAxclR0NFExVWhRQWxpd2tZSGlUbW5RQTUzTEs5Uy9rWFNFOFBmSVdFVUpSdzZFSjAzT2dSa2EKVTYvN09DK1J1Y2cxaGJRVUZmSzFFVmtzVVJtSjkxbVE0RDdERk5jYTdzQmkzTTFVR2p4ais3S0ttL0VSR1RqYwpFa1d1WXFUZndqN3NqakFnU3dMeGZ5cnJZbTBGSFNBMnB1RmNUZWlEdDZOclFJVkJDaktOQUduR2t0cDEvQ1UxCjk1azlJbzl2dmNVaWRraE9nbFpwdDlYQmNvU3V2S2JUVk9UektyTDRwaGtkTlFwUWwwekRqL3l6eTJ3Q1RNL2cKK2hsQ1N6RGN5ZERSM1ZEaHhwd3ljdjV6ZU1kM1dZVlJRL0tiZmhldlo1N0pocVlySitsaUkxMFFnMm5CeVZ5NQoxREpCQ2JDTXg3dklxVURHazIvaXlIU3dmWkpOK3VNUjUzYyt6ZUZFdzA5aVdTd2ZxN21LcXV4b0laR0dHUGZjCmRKU3N6OC8ybjl0cTNDTHBLL0lFZ3lleTQ1ZFgxOTNtVGhtc1JOcHFrQ2h1Wlgrc1k5cHowdXEwVERpNkhDOWgKWGZrcEozaU93M25uL2t6V1J6M3NPdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      url: https://localhost:5443/webhook/flowcontrol-guardrails
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: flowcontrol-guardrails.common-webhooks.networking.gke.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
    - apiGroups:
      - flowcontrol.apiserver.k8s.io
      apiVersions:
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      - DELETE
      resources:
      - prioritylevelconfigurations
      - flowschemas
      scope: '*'
    sideEffects: None
    timeoutSeconds: 45
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    annotations:
      meta.helm.sh/release-name: nginx
      meta.helm.sh/release-namespace: nginx
    creationTimestamp: "2022-10-17T10:45:54Z"
    generation: 2
    labels:
      app.kubernetes.io/component: admission-webhook
      app.kubernetes.io/instance: nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.4.0
      helm.sh/chart: ingress-nginx-4.3.0
    name: nginx-ingress-nginx-admission
    resourceVersion: "59312"
    uid: a5367f35-aa82-4717-bd1a-403e0331a6a8
  webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkVENDQVJ5Z0F3SUJBZ0lSQU9qZStlV2sxRHRtZDBjTzIrS0JMcXN3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FYm1sc01UQWdGdzB5TWpFd01UY3hNRFF3TkRsYUdBOHlNVEl5TURreU16RXdOREEwT1ZvdwpEekVOTUFzR0ExVUVDaE1FYm1sc01UQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJMcTd2OWVxCm5sL2dVZGZoVHM4dUlYZ2RVSGpGTTQrU0cvT21XRTJWUDFlMWVzZkpYL3o5Vno3b2ZtZnJjMGNCeGUwL0VLQjkKK3EyOXlBVlpubVRsd0dPalZ6QlZNQTRHQTFVZER3RUIvd1FFQXdJQ0JEQVRCZ05WSFNVRUREQUtCZ2dyQmdFRgpCUWNEQVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRaUhiMkhIc1lvSU5ueUVPYkMyeG5VCkxNRXBDVEFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUJ1M3FvdWhCVEpPT2dweG1yN3Y0MHZKNFExbWNQVDBMdXkKK0JaNGFWdkRMZ0lnTEJvUklobkZMTU01Ym00QUprdjFhZUl3djdnaFBrdW5RU2U0bDRRTnlnQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: nginx-ingress-nginx-controller-admission
        namespace: nginx
        path: /networking/v1/ingresses
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validate.nginx.ingress.kubernetes.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
    - apiGroups:
      - networking.k8s.io
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - ingresses
      scope: '*'
    sideEffects: None
    timeoutSeconds: 45
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    creationTimestamp: "2022-10-17T08:45:46Z"
    generation: 1
    labels:
      networking.gke.io/common-webhooks: "true"
    name: nodelimit.config.common-webhooks.networking.gke.io
    resourceVersion: "842"
    uid: 881144a2-dac6-4bd1-a033-4e370e0d66c2
  webhooks:
  - admissionReviewVersions:
    - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRTW4yZ0VFQ1Z5VlFncDc0SU00VTh1REFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRd016UTJPR05pWWkxbE9Ua3hMVFJpTldZdFlUUTFOaTAzT0RFNE9EZzJOekEwTUdRdwpJQmNOTWpJeE1ERTNNRGMwTURBNVdoZ1BNakExTWpFd01Ea3dPRFF3TURsYU1DOHhMVEFyQmdOVkJBTVRKREF6Ck5EWTRZMkppTFdVNU9URXROR0kxWmkxaE5EVTJMVGM0TVRnNE9EWTNNRFF3WkRDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU10YVJuMW40OTl3WWJWQzdkVUtBcTNIaDUwM0xCZzRwUnNPNlN5UQo4dTFCR0s0VkdGYlhoZTNuaHpTaDRIcmo0VmlmRUJmLzY0ZFRjVUpNUHhjVEMwZ1JJVGtHMXhvQ1JhL3Rjb2twCjhYTVJWdC9hUHg5UzdDUlhoM0R3bEprRXJoSkF5TWZhdXNEVnBzZHNxTlNrcXByMVFoeXBIbHZGTHlwMEZQWEoKSVB2cE1VYXhkVkUwRlB3VTVnK29QOGFQOWkySTJxMFRWYWl1Zkg0VTFpMitIMnNHSjdFeUlOLzQ0Wm0rM1Y4TgpEd1J6OWNzcmJvb2tDUDlkZ0dVMDU5OEx5cGZQUDN1SDVLSEUrT0hQVWVLSkQ3cGQvdlovaWhmMGpLME82UVFQCmdHTlhuSDlGNUE1Nk1iTkhLOENYOWU4aytZY25DTHUxbktEWVV6clMvMDJYWjF0dkNXRkFIcFZ1M0lEQ1g0RkQKTEFoY3NmenhuTitKUW9tbGUvOVpzNnlieE0wUXpDdzJMQUVScjhmTkpHdmQ1YTNwRW14WUJKYWNpVGdhZGlUMwpFcUVMUUJqdk9JbVh0bllZR2xZZk40N1hzTkd3eWVzQzVYekxYdFBKanJtZEpCaW1ZWVNqSllGbnF5NnhTbmZPCi8yYmEvUWJIaEY2Nk5HdWFxNmpuRHhDMzB3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVIYjFoWWxiQ2VXZnMwUnMvMlZQS1RWaHNMSFV3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFGTDVEb2FDYS81RllxQnE5bjc5MDlDcnJmQjh5am1lZWlqeFdpM0phODNaCnZsNjA4V0pWQjAxclR0NFExVWhRQWxpd2tZSGlUbW5RQTUzTEs5Uy9rWFNFOFBmSVdFVUpSdzZFSjAzT2dSa2EKVTYvN09DK1J1Y2cxaGJRVUZmSzFFVmtzVVJtSjkxbVE0RDdERk5jYTdzQmkzTTFVR2p4ais3S0ttL0VSR1RqYwpFa1d1WXFUZndqN3NqakFnU3dMeGZ5cnJZbTBGSFNBMnB1RmNUZWlEdDZOclFJVkJDaktOQUduR2t0cDEvQ1UxCjk1azlJbzl2dmNVaWRraE9nbFpwdDlYQmNvU3V2S2JUVk9UektyTDRwaGtkTlFwUWwwekRqL3l6eTJ3Q1RNL2cKK2hsQ1N6RGN5ZERSM1ZEaHhwd3ljdjV6ZU1kM1dZVlJRL0tiZmhldlo1N0pocVlySitsaUkxMFFnMm5CeVZ5NQoxREpCQ2JDTXg3dklxVURHazIvaXlIU3dmWkpOK3VNUjUzYyt6ZUZFdzA5aVdTd2ZxN21LcXV4b0laR0dHUGZjCmRKU3N6OC8ybjl0cTNDTHBLL0lFZ3lleTQ1ZFgxOTNtVGhtc1JOcHFrQ2h1Wlgrc1k5cHowdXEwVERpNkhDOWgKWGZrcEozaU93M25uL2t6V1J6M3NPdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      url: https://localhost:5443/webhook/nodelimit
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: nodelimit.common-webhooks.networking.gke.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - nodes
      scope: '*'
    sideEffects: None
    timeoutSeconds: 45
- apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    annotations:
      components.gke.io/layer: addon
    creationTimestamp: "2022-10-17T08:45:48Z"
    generation: 1
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
    name: validation-webhook.snapshot.storage.k8s.io
    resourceVersion: "882"
    uid: 4c5c2c64-10cb-47fd-9eb3-b34e51b801e4
  webhooks:
  - admissionReviewVersions:
    - v1
    - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRTW4yZ0VFQ1Z5VlFncDc0SU00VTh1REFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRd016UTJPR05pWWkxbE9Ua3hMVFJpTldZdFlUUTFOaTAzT0RFNE9EZzJOekEwTUdRdwpJQmNOTWpJeE1ERTNNRGMwTURBNVdoZ1BNakExTWpFd01Ea3dPRFF3TURsYU1DOHhMVEFyQmdOVkJBTVRKREF6Ck5EWTRZMkppTFdVNU9URXROR0kxWmkxaE5EVTJMVGM0TVRnNE9EWTNNRFF3WkRDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU10YVJuMW40OTl3WWJWQzdkVUtBcTNIaDUwM0xCZzRwUnNPNlN5UQo4dTFCR0s0VkdGYlhoZTNuaHpTaDRIcmo0VmlmRUJmLzY0ZFRjVUpNUHhjVEMwZ1JJVGtHMXhvQ1JhL3Rjb2twCjhYTVJWdC9hUHg5UzdDUlhoM0R3bEprRXJoSkF5TWZhdXNEVnBzZHNxTlNrcXByMVFoeXBIbHZGTHlwMEZQWEoKSVB2cE1VYXhkVkUwRlB3VTVnK29QOGFQOWkySTJxMFRWYWl1Zkg0VTFpMitIMnNHSjdFeUlOLzQ0Wm0rM1Y4TgpEd1J6OWNzcmJvb2tDUDlkZ0dVMDU5OEx5cGZQUDN1SDVLSEUrT0hQVWVLSkQ3cGQvdlovaWhmMGpLME82UVFQCmdHTlhuSDlGNUE1Nk1iTkhLOENYOWU4aytZY25DTHUxbktEWVV6clMvMDJYWjF0dkNXRkFIcFZ1M0lEQ1g0RkQKTEFoY3NmenhuTitKUW9tbGUvOVpzNnlieE0wUXpDdzJMQUVScjhmTkpHdmQ1YTNwRW14WUJKYWNpVGdhZGlUMwpFcUVMUUJqdk9JbVh0bllZR2xZZk40N1hzTkd3eWVzQzVYekxYdFBKanJtZEpCaW1ZWVNqSllGbnF5NnhTbmZPCi8yYmEvUWJIaEY2Nk5HdWFxNmpuRHhDMzB3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVIYjFoWWxiQ2VXZnMwUnMvMlZQS1RWaHNMSFV3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFGTDVEb2FDYS81RllxQnE5bjc5MDlDcnJmQjh5am1lZWlqeFdpM0phODNaCnZsNjA4V0pWQjAxclR0NFExVWhRQWxpd2tZSGlUbW5RQTUzTEs5Uy9rWFNFOFBmSVdFVUpSdzZFSjAzT2dSa2EKVTYvN09DK1J1Y2cxaGJRVUZmSzFFVmtzVVJtSjkxbVE0RDdERk5jYTdzQmkzTTFVR2p4ais3S0ttL0VSR1RqYwpFa1d1WXFUZndqN3NqakFnU3dMeGZ5cnJZbTBGSFNBMnB1RmNUZWlEdDZOclFJVkJDaktOQUduR2t0cDEvQ1UxCjk1azlJbzl2dmNVaWRraE9nbFpwdDlYQmNvU3V2S2JUVk9UektyTDRwaGtkTlFwUWwwekRqL3l6eTJ3Q1RNL2cKK2hsQ1N6RGN5ZERSM1ZEaHhwd3ljdjV6ZU1kM1dZVlJRL0tiZmhldlo1N0pocVlySitsaUkxMFFnMm5CeVZ5NQoxREpCQ2JDTXg3dklxVURHazIvaXlIU3dmWkpOK3VNUjUzYyt6ZUZFdzA5aVdTd2ZxN21LcXV4b0laR0dHUGZjCmRKU3N6OC8ybjl0cTNDTHBLL0lFZ3lleTQ1ZFgxOTNtVGhtc1JOcHFrQ2h1Wlgrc1k5cHowdXEwVERpNkhDOWgKWGZrcEozaU93M25uL2t6V1J6M3NPdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      url: https://localhost:23011/volumesnapshot
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: validation-webhook.snapshot.storage.k8s.io
    namespaceSelector: {}
    objectSelector: {}
    rules:
    - apiGroups:
      - snapshot.storage.k8s.io
      apiVersions:
      - v1
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - volumesnapshots
      - volumesnapshotcontents
      scope: '*'
    sideEffects: None
    timeoutSeconds: 45
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
